CC=g++
CFLAGS= --std=c++17 -g -Wall

.SILENT: default 1
.PHONY: default 1

default:
	echo "usage: make {day}"

1:
	$(CC) $(CFLAGS) day1.cpp && ./a.out 1.txt

2:
	$(CC) $(CFLAGS) day2.cpp && ./a.out 2.txt

3:
	$(CC) $(CFLAGS) day3.cpp && ./a.out 3.txt

4:
	$(CC) $(CFLAGS) day4.cpp && ./a.out 4.txt

5:
	$(CC) $(CFLAGS) day5.cpp && ./a.out 5.txt

6:
	$(CC) $(CFLAGS) day6.cpp && ./a.out 6.txt

7:
	$(CC) $(CFLAGS) day7.cpp && ./a.out 7.txt

8:
	$(CC) $(CFLAGS) day8.cpp && ./a.out 8.txt

9:
	$(CC) $(CFLAGS) day9.cpp && ./a.out 9.txt

10:
	$(CC) $(CFLAGS) day10.cpp && ./a.out 10.txt

11:
	$(CC) $(CFLAGS) day11.cpp && ./a.out 11.txt

12:
	$(CC) $(CFLAGS) day12.cpp && ./a.out 12.txt

13:
	$(CC) $(CFLAGS) day13.cpp && ./a.out 13.txt

14:
	$(CC) $(CFLAGS) day14.cpp && ./a.out 14.txt

15:
	$(CC) $(CFLAGS) day15.cpp && ./a.out 15.txt

16:
	$(CC) $(CFLAGS) day16.cpp && ./a.out 16.txt

17:
	$(CC) $(CFLAGS) day17.cpp && ./a.out 17.txt

18:
	$(CC) $(CFLAGS) day18.cpp && ./a.out 18.txt

19:
	$(CC) $(CFLAGS) day19.cpp && ./a.out 19.txt

20:
	$(CC) $(CFLAGS) day20.cpp && ./a.out 20.txt

21:
	$(CC) $(CFLAGS) day21.cpp && ./a.out 21.txt

22:
	$(CC) $(CFLAGS) day22.cpp && ./a.out 22.txt

23:
	$(CC) $(CFLAGS) day23.cpp && ./a.out 23.txt

24:
	$(CC) $(CFLAGS) day24.cpp && ./a.out 24.txt

25:
	$(CC) $(CFLAGS) day25.cpp && ./a.out 25.txt
